pipeline {

    agent any

    stages {

        stage('Deploy to EC2') {
            steps {
                sshagent(['ec2-teamhub']) {
                    bat '''
                        ssh -o StrictHostKeyChecking=no ubuntu@3.85.115.97 "cd ~/three-tier-webapp && git pull origin main && docker compose up -d --build"
                    '''
                }
            }
        }

        stage('Verify Deployment') {
            steps {
                sshagent(['ec2-teamhub']) {
                    bat '''
                        ssh -o StrictHostKeyChecking=no ubuntu@3.85.115.97 "cd ~/three-tier-webapp && docker compose ps"
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'TeamHub deployed successfully to EC2!'
        }

        failure {
            echo 'TeamHub deployment failed!'
        }
    }
}